# Generated by Django 5.2.7 on 2026-02-26 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0012_userprofile_last_activity_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodlog',
            name='mood_label',
            field=models.CharField(choices=[('Joyful', 'Joyful'), ('Excited', 'Excited'), ('Energetic', 'Energetic'), ('Proud', 'Proud'), ('Happy', 'Happy'), ('Grateful', 'Grateful'), ('Loved', 'Loved'), ('Calm', 'Calm'), ('Relaxed', 'Relaxed'), ('Neutral', 'Neutral'), ('Focused', 'Focused'), ('Sad', 'Sad'), ('Lonely', 'Lonely'), ('Grief', 'Grief'), ('Angry', 'Angry'), ('Frustrated', 'Frustrated'), ('Anxious', 'Anxious'), ('Stressed', 'Stressed'), ('Overwhelmed', 'Overwhelmed'), ('Tired', 'Tired')], max_length=20),
        ),
        migrations.CreateModel(
            name='Journal2Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='journal2/voice/')),
                ('face_capture', models.ImageField(blank=True, null=True, upload_to='journal2/face/')),
                ('face_emotion', models.CharField(blank=True, max_length=50)),
                ('text_emotion', models.CharField(blank=True, max_length=50)),
                ('voice_emotion', models.CharField(blank=True, max_length=50)),
                ('final_emotion', models.CharField(blank=True, max_length=50)),
                ('analysis_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
