# Generated by Django 5.2.7 on 2026-03-28 03:05

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0013_alter_moodlog_mood_label_journal2entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundmusic',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='background_music/'),
        ),
        migrations.AlterField(
            model_name='emotionjournal',
            name='voice',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='journal/voice/'),
        ),
        migrations.AlterField(
            model_name='journal2entry',
            name='voice_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='journal2/voice/'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='meditations/'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='music_tracks/'),
        ),
        migrations.AlterField(
            model_name='stressbustersession',
            name='voice_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='stress_buster/'),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='therapy_music/'),
        ),
        migrations.AlterField(
            model_name='yogasession',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='yoga/'),
        ),
    ]
